document.write('<!-- The site footer, where most of the JavaScript is loaded -->');
document.write('<style>');
document.write('.badges');
document.write('{');
document.write('	display: flex;');
document.write('	justify-content: center;');
document.write('	flex-wrap: wrap;');
document.write('}');
document.write('</style>');
document.write('<section class="footer">');
document.write('	<hr>');
document.write('	<div class="badges">');
document.write('		<img src=/common/images/badges/firefoxnow.gif />&nbsp');
document.write('		<img src=/common/images/badges/netscapenow.gif />&nbsp ');
document.write('		<img src=/common/images/badges/php.gif />&nbsp');
document.write('		<img src=/common/images/badges/geocities.gif />&nbsp');
document.write('		<img src=/common/images/badges/neocities.gif />&nbsp');
document.write('		<img src=/common/images/badges/vim.gif />');
document.write('	</div>');
document.write('	<p style="text-align: center;">Copyright Bad64 2025<br>And remember...</p>');
document.write('	<div class="badges">');
document.write('		<img src=/common/images/badges/chromevil.gif />');
document.write('	</div>');
document.write('	<p style="text-align: center;"><a href="#">Back to top</a></p>');
document.write('</section>');
document.write('');
document.write('<script src="/common/elements/scripts.js"></script>');
