document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('	<head>');
document.write('		<title></title>');
document.write('		<link rel="stylesheet" href="/common/styles/layout.css">');
document.write('		<link rel="stylesheet" href="/common/styles/styles.css">');
document.write('		<link rel="stylesheet" href="/common/styles/anims.css">');
document.write('	</head>');
document.write('	<body>');
document.write('		<!--#include virtual="/common/elements/html/sidenav.shtml"-->');
document.write('');
document.write('		<div class="content">');
document.write('			<!--#include virtual="/common/elements/html/topnav.shtml"-->');
document.write('');
document.write('			<article class="blogpost">');
document.write('				<div class="titlebar">');
document.write('					<label class="title"></label>');
document.write('					<div class="buttoncontainer">');
document.write('						<label class="fakebutton">X</label>');
document.write('					</div>');
document.write('				</div>');
document.write('				');
document.write('				<!--#include virtual="/common/elements/html/fakemenu.shtml"-->');
document.write('');
document.write('				<p>');
document.write('                		</p>');
document.write('			</article>');
document.write('			<!--#include virtual="/common/elements/html/footer.shtml"-->');
document.write('		</div>');
document.write('	</body>');
document.write('</html>');
